version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile   # or Dockerfile.standalone if you split them
    image: dss-web:latest
    restart: unless-stopped
    ports:
      - "3003:3000"
    env_file:
      - .env.local
    environment:
      NODE_ENV: production
      PORT: 3000
      # If you don’t use env_file, set vars directly here.

    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:3000/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s

